spring:
  application:
    name: py-sidecar
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true

server:
  port: 8001

sidecar:
  port: 3000
  health-uri: http://127.0.0.1:${sidecar.port}/health
