eureka:
  instance:
    hostname: localhost
  #    prefer-ip-address: true
#    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance-id}:${server.port}
#    hostname: ${spring.cloud.client.ip-address}
#    lease-renewal-interval-in-seconds: 1
#    lease-expiration-duration-in-seconds: 2
  client:
    #fetch-registry: false
    #register-with-eureka: false
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@localhost:9001/eureka/

spring:
  security:
    user:
      name: admin
      password: 123456
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false