eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance-id}:${server.port}
    hostname: ${spring.cloud.client.ip-address}
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
  client:
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@localhost:9009/eureka/

spring:
  security:
    user:
      name: admin
      password: ENC(0+DVIbbR5ZgdwQCSaJS9MA==) # 不加密在服务器限制ip访问
  profiles:
    include: im-prod,feign-prod
  datasource:
    url: jdbc:mysql://localhost:3306/rngay_quartz?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false&autoReconnect=true&rewriteBatchedStatements=true
    username: root
    password: ENC(VXWXDh5zyOR8haV8/YjtCCZ+oIOVpRk2) # 启动服务时手动加盐，防止被解密
