spring:
  application:
    name: platform
  profiles:
    active: dev
    include: feign-${spring.profiles.active}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    database: mysql
    hibernate:
      ddl-auto: update
  resources:
    static-locations: classpath:/static/, classpath:/views/
  main:
    allow-bean-definition-overriding: true
  mvc:
    dispatch-options-request: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
server:
  port: 9090

jwt:
  secret: f4e2e52034348f86b67cde581c0f9eb5
  expire: 604800
  header: token