eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance-id}:${server.port}
    hostname: ${spring.cloud.client.ip-address}
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
  client:
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@localhost:9009/eureka/

spring:
  jpa:
    show-sql: true
  security:
    user:
      name: admin
      password: 123456 # 不加密在服务器限制ip访问
  datasource:
    url: jdbc:mysql://localhost:3306/rngay_platform?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: ENC(wYs42725uxJOUlaoRudB0TQ9KeKNW5bTbmeXKKfYqlE=) # 启动服务时手动加盐，防止被解密
  redis:
    database: 2
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 1ms

platform:
  clearUrlOnRestart: false
