spring:
  application:
    name: authority
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    database: mysql
    hibernate:
      ddl-auto: update
  resources:
    static-locations: classpath:/static/, classpath:/views/
  mvc:
    dispatch-options-request: true
  main:
    allow-bean-definition-overriding: true
server:
  port: 9090

jwt:
  secret: f4e2e52034348f86b67cde581c0f9eb5
  expire: 604800
  header: token

exception:
  msg: true

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.rngay.feign.authority
  global-config:
    db-config:
      id-type: id_worker
    worker-id: 1
    datacenter-id: 18
