eureka:
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 4000
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance-id}:${server.port}
    hostname: ${spring.cloud.client.ip-address}
  client:
    fetch-registry: false #是否从eureka上获取注册信息
    register-with-eureka: false #是否注册自己到eureka服务器
    service_url:
      default_zone: http://${spring.security.user.name}:${spring.security.user.password}@localhost:9001/eureka/

spring:
  security:
    user:
      name: admin
      password: 123456