spring:
  jpa:
    show-sql: true
  profiles:
    include: feign-prod
  security:
    user:
      name: admin
      password: 123456 # 不加密在服务器限制ip访问
  datasource:
    url: jdbc:mysql://localhost:3306/rngay_platform?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false&autoReconnect=true&rewriteBatchedStatements=true
    username: root
    password: ENC(VXWXDh5zyOR8haV8/YjtCCZ+oIOVpRk2) # 启动服务时手动加盐，防止被解密
  redis:
    database: 2
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 1ms
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: authority
          uri: lb://service-authority
          predicates:
            - Path=/authority/**
            - Authorize=true
          filters:
            - StripPrefix=1
            - name: Hystrix
                args:
                  name: authorityHystrix
                  fallbackUri: 'forward:/defaultFallback'
        - id: user
          uri: lb://service-user
          predicates:
            - Path=/user/**
            - Authorize=true
          filters:
            - StripPrefix=1
            - name: Hystrix
                args:
                  name: authorityHystrix
                  fallbackUri: 'forward:/defaultFallback'