spring:
  jpa:
    show-sql: true
  security:
    user:
      name: admin
      password: 123456
  datasource:
    url: jdbc:mysql://localhost:3306/rngay_platform?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false&autoReconnect=true&rewriteBatchedStatements=true
    username: root
    password: root
  redis:
    database: 2
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 1ms
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: authority
          uri: lb://service-authority
          predicates:
            - Path=/authority/**
          filters:
            - StripPrefix=1
            - Authorize=true
            - name: Hystrix
              args:
                name: authorityHystrix
                fallbackUri: 'forward:/defaultFallback'
        - id: user
          uri: lb://service-user
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
            - Authorize=true
            - name: Hystrix
              args:
                name: userHystrix
                fallbackUri: 'forward:/defaultFallback'

#hystrix:
#  shareSecurityContext: true
#  metrics:
#    enabled: true
#    polling-interval-ms: 5000 # 设置默认超时时间为5s

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 3000

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl