feign:
  httpclient:
    enabled: true
#  client:
#    config:
#      default:
#        connect-timeout: 1000
#        read-timeout: 5000
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 4000
      fallback:
        isolation:
          semaphore:
            maxConcurrentRequests: 200
      requestCache:
        enabled: true
      circuitBreaker:
        forceClosed: false
  threadpool:
    default:
      coreSize: 20
      maximumSize: 200
      maxQueueSize: 1000
      queueSizeRejectionThreshold: 1000
spring:
  cloud:
    loadbalancer:
      retry:
        enabled: true
ribbon:
  ConnectTimeout: 2000
  ReadTimeout: 3000
  OkToRetryOnAllOperations: true  #对所有操作请求都进行重试,默认false
  MaxAutoRetriesNextServer: 3
  MaxAutoRetries: 3