spring:
  rabbitmq:
    host: 47.98.232.27
    username: jiaozibao
    password: root369369
    port: 5672
    publisher-confirms: true #支持发布确认
    publisher-returns: true #支持发布返回
    listener:
      simple:
        acknowledge-mode: manual #采用手动应答
        concurrency: 1 #指定最小的消费者数量
        max-concurrency: 1 #指定最大的消费者数量
        retry:
          enabled: true #是否支持重试